version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: 'npm run'
          cypress-command: 'npx cypress run --parallel --record --group all tests'
          parallelism: 3
