version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: 'npm run'
          cypress-command: 'npx cypress run --parallel --record --key a186d5e2-e67a-471d-bc7e-f84b0c3b0ec0 --group all tests'
          parallelism: 3
